# ansible\playbooks\setup_haproxy_keepalived_full.yml
---
- name: "Playbook maestro: Instalar HAProxy + Keepalived + Scripts de Notificación"
  import_playbook: create_keepalived_notify_scripts.yml

- name: "Instalar servicios y configuración de HAProxy + Keepalived"
  import_playbook: haproxy_keepalived.yml